### ISSUE TITLE
regex transformations containing commas are not parsed properly

### ISSUE THREAD

**Issue by csdev** [vail130/composable-js#4]
https://github.com/vail130/composable-js/blob/02c3a2c76aa46f964fa24492aba5aebde4cfb937/composable.js#L241

For example, consider the transformation `"replace:/a{1,2}/,b"`
Expected parse: `replace(/a{1,2}/, "b")`
Actual, broken parse: `replace("/a{1", "2}/", "b")`

**Comment by vail130** [comment]
9779fcaa0d1166934e67a5edc5d72f85cd75a693

Fixed.
