### ISSUE TITLE
Over aggressive regex matching when parsing arguments

### ISSUE THREAD

**Issue by jonathan-ostrander** [vail130/composable-js#9]
For example:

`replace:/^https?:\/\/(www\.)?/i,http://` on the string `"https://www.modaoperandi.com/ca-lou-springsummer-2013/silver-and-crystal-alexandra-tempestato-earrings"` should return `"http://modaoperandi.com/ca-lou-springsummer-2013/silver-and-crystal-alexandra-tempestato-earrings"`, but instead returns `"http:////www.modaoperandi.com/ca-lou-springsummer-2013/silver-and-crystal-alexandra-tempestato-earrings"`

The logic used to parse the arguments for a command, when they use regex, are over aggressive when trying to match the regex part of the [extractArgs](https://github.com/vail130/composable-js/blob/master/composable.js#L307) method.

**Comment by vail130** [comment]
c395eeb25d29b96db36131590fc467e87817406c

Done
